"""add indexes and use clock_timestamp

Revision ID: 540776e2bac0
Revises: df450fa75991
Create Date: 2026-06-07 13:45:55.293424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540776e2bac0'
down_revision: Union[str, None] = 'df450fa75991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_books_author_id', 'books', ['author_id'], unique=False)
    op.create_index('ix_books_year', 'books', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_books_year', table_name='books')
    op.drop_index('ix_books_author_id', table_name='books')
    # ### end Alembic commands ###
